### ISSUE TITLE
Make `/create_group` slash command case insensitive for roles

### ISSUE THREAD

**Issue by grantmwilson** [engfrosh/discord-bot#1]
I'm getting a lot of this response when trying to add groups without looking at the role list
![image](https://user-images.githubusercontent.com/81658019/210244963-8ea2da74-e7c7-4767-ba53-abaf6c22833b.png)

**Comment by finlaywashere** [comment]
Resolved in commit 6eaa46ea2596fa5848985b146cbfc7cd40db8f21 by making create group force all names to lower case before looking up roles
