### ISSUE TITLE
Discord command `/create_role`  change default case from lowercase to titlecase

### ISSUE THREAD

**Issue by grantmwilson** [engfrosh/discord-bot#2]
ie. currently will create `spirit` but `Spirit` would look nicer even if it does make typing it for commands a touch harder

**Comment by finlaywashere** [comment]
This is fixed in commit 02c311220457c0084b2f39061da8c7975d2d4ca4 by changing the role names to title case. The category names have been left as lower case to avoid having to change a lot of them as they show up in all caps anyway
