### ISSUE TITLE
When running `/purge` the bot doesn't respond

### ISSUE THREAD

**Issue by grantmwilson** [engfrosh/discord-bot#3]
The command works as desired, it just doesn't respond to the interaction, instead showing this:
![image](https://user-images.githubusercontent.com/81658019/210246107-6a71820f-080a-45ee-b5fa-1412e132e26f.png)

**Comment by finlaywashere** [comment]
Fixed this in 3ee1c59e96b16cff8c600fb7bb8e61c98038faf9 by making it actually respond on success
